version: '3.3'
services:
    rspace-app:
      restart: always
      image: 'tomcat:9-jre17'
      container_name: rspace-app
      volumes:
        - type: bind
          source: rspace.war
          target: /usr/local/tomcat/webapps/ROOT.war
        - type: bind
          source: deployment.properties
          target: /etc/rspace/deployment.properties
        - type: bind
          source: configs/rspace.env
          target: /usr/local/tomcat/bin/setenv.sh
        - type: bind
          source: configs/tomcat-locate.sh
          target: /usr/libexec/tomcat9/tomcat-locate-java.sh
        - type: bind
          source: configs/server.xml
          target: /usr/local/tomcat/conf/server.xml
        - type: volume
          source: rspace-media
          target: /media/rspace
      ports:
        - '8080:8080'
    rspace-db:
      image: 'mariadb:lts-jammy'
      restart: always
      container_name: rspace-db
      volumes:
        - type: volume
          source: rspace-db
          target: /var/lib/mysql
        - type: bind
          source: configs/db-config.cnf
          target: /etc/alternatives/my.cnf
        - type: bind
          source: templates/db-template.sql
          target: /import.sql
      environment:
          MARIADB_ROOT_PASSWORD: rspacedocker
          MARIADB_DATABASE: rspace
          MARIADB_USER: rspacedocker
          MARIADB_PASSWORD: rspacedocker
      command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

volumes:
  rspace-media:
  rspace-db:
