services:
    rspace-app:
      restart: always
      image: 'tomcat:9-jre17'
      container_name: rspace-app
      volumes:
        - type: bind
          source: ./rspace.war
          target: /usr/local/tomcat/webapps/ROOT.war
        - type: bind
          source: ./deployment.properties
          target: /etc/rspace/deployment.properties
        - type: bind
          source: ./configs/rspace.env
          target: /usr/local/tomcat/bin/setenv.sh
        - type: bind
          source: ./configs/tomcat-locate.sh
          target: /usr/libexec/tomcat9/tomcat-locate-java.sh
        - type: bind
          source: ./configs/server.xml
          target: /usr/local/tomcat/conf/server.xml
        - type: volume
          source: rspace-media
          target: /media/rspace
      ports:
        - '8080:8080'
      depends_on:
        prep-dirs:
          condition: service_completed_successfully
        rspace-db:
          condition: service_healthy
    prep-dirs:
      image: 'ubuntu:24.04'
      volumes:
        - type: volume
          source: rspace-media
          target: /media/rspace
      command: >
        mkdir -pv
          /media/rspace/archive
          /media/rspace/archives
          /media/rspace/backup
          /media/rspace/download
          /media/rspace/file_store
          /media/rspace/FTsearchIndices
          /media/rspace/indices
          /media/rspace/jmelody
          /media/rspace/logs-audit
          /media/rspace/LuceneFTsearchIndices
          /media/rspace/tomcat-tmp
    rspace-db:
      image: 'mariadb:lts-jammy'
      restart: always
      container_name: rspace-db
      volumes:
        - type: volume
          source: rspace-db
          target: /var/lib/mysql
        - type: bind
          source: ./configs/db-config.cnf
          target: /etc/alternatives/my.cnf
        - type: bind
          source: ./templates/db-template.sql
          target: /docker-entrypoint-initdb.d/import.sql
      environment:
          MARIADB_ROOT_PASSWORD: rspacedocker
          MARIADB_DATABASE: rspace
          MARIADB_USER: rspacedocker
          MARIADB_PASSWORD: rspacedocker
      command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3

volumes:
  rspace-media:
  rspace-db:
